opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing

disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - nesting
  - todo
  - type_body_length
  - type_name

included:
  - iosApp
